name: Sanity Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Set environment
        run: echo "SANITY_STUDIO_API_ENVIRONMENT=${{ github.event.inputs.environment || 'production' }}" >> $GITHUB_ENV
      
      - name: Build
        run: npm run build
      
      - name: Deploy to Sanity
        run: npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_API_ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}
      
      - name: Deploy GraphQL API
        run: npm run deploy-graphql
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_API_ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}